// Projects + experience data for Hicham's portfolio

const PROJECTS = [
  {
    id: "ledger-os",
    num: "01",
    title: "Ledger OS",
    subtitle: "A real-time financial reconciliation platform",
    year: "2024",
    role: "Lead Engineer",
    timeline: "8 months",
    tools: "TypeScript · PostgreSQL · Kafka · React",
    tags: ["Backend", "Distributed Systems", "Fintech"],
    desc: "Rebuilt a legacy nightly batch system into an event-streamed ledger that reconciles 4M+ transactions per day in under 200ms.",
    art: "art-1",
    overview: "Ledger OS replaces a 12-year-old nightly batch reconciliation system with an event-driven platform. It ingests transaction streams from 14 upstream sources, applies a deterministic state machine, and emits balanced ledger entries in near real time.",
    problem: "The legacy system batched reconciliation overnight. By morning, ops teams faced thousands of mismatches with no signal to which upstream caused them. Outages cascaded, audits slipped, and growth was hard-capped by the batch window.",
    process: "I led a 4-engineer team through a 6-month rebuild. We modeled every transaction as an immutable event, replayed eight years of history through the new pipeline to validate correctness against the legacy outputs, then ran both systems in parallel for two months before cutover. Key decisions: Kafka for the spine, a Postgres write-side for the canonical ledger, and a derived read-side optimized for ops dashboards.",
    outcomes: [
      { v: "200ms", k: "P99 Reconcile Latency", d: "Down from a 6-hour batch window." },
      { v: "4M/day", k: "Transactions Processed", d: "With headroom for 10x growth." },
      { v: "$2.1M", k: "Saved Annually", d: "Through reduced ops overhead and fewer escalations." },
    ],
  },
  {
    id: "atlas",
    num: "02",
    title: "Atlas",
    subtitle: "Workflow automation for engineering teams",
    year: "2023",
    role: "Founding Engineer",
    timeline: "11 months",
    tools: "Go · React · gRPC · Docker",
    tags: ["Full Stack", "DevTools", "Automation"],
    desc: "A workflow engine that lets engineers describe pipelines in YAML and run them across hybrid infrastructure with zero-config rollback.",
    art: "art-2",
    overview: "Atlas is an internal automation platform replacing a sprawl of bash scripts, Jenkins pipelines, and Airflow DAGs with a single declarative engine. Engineers describe what they want; Atlas figures out how, where, and when.",
    problem: "Each team had reinvented its own deploy and data pipeline. Cross-team handoffs broke constantly because no two pipelines shared the same primitives. We had three incidents in one quarter caused by drift between staging and prod scripts.",
    process: "I designed the YAML schema and the Go execution engine, built the React control plane, and partnered with five teams to migrate their workflows. We started with a single team's pipeline as the design partner, shipped a v0 in six weeks, and onboarded the rest over the year.",
    outcomes: [
      { v: "5 → 1", k: "Tools Consolidated", d: "Replaced Jenkins, Airflow, and three internal scripts." },
      { v: "73%", k: "Faster Deploys", d: "Median pipeline runtime dropped from 22 to 6 minutes." },
      { v: "0", k: "Drift Incidents", d: "In the 12 months following rollout." },
    ],
  },
  {
    id: "signalbox",
    num: "03",
    title: "Signalbox",
    subtitle: "Observability for embedded fleets",
    year: "2023",
    role: "Senior Engineer",
    timeline: "5 months",
    tools: "Rust · WebAssembly · TimescaleDB",
    tags: ["Embedded", "Observability", "Rust"],
    desc: "A telemetry pipeline for industrial IoT that compresses sensor streams 80x at the edge and surfaces anomalies in seconds.",
    art: "art-3",
    overview: "Signalbox watches a fleet of 12,000 industrial controllers across three continents. Edge agents written in Rust compress and forward telemetry; a central pipeline stores and queries it in Timescale.",
    problem: "Bandwidth at remote sites was the bottleneck. Raw sensor streams cost more in egress than the controllers themselves were billed at, and the legacy stack dropped data during network blips with no recovery.",
    process: "I prototyped the edge agent in Rust to evaluate compression strategies, landed on a domain-specific delta encoding that exploits the slow drift of industrial signals, and built a WASM-based query language so analysts could write filters once and run them at the edge or in the cloud.",
    outcomes: [
      { v: "80×", k: "Compression Ratio", d: "Median across the deployed fleet." },
      { v: "12k", k: "Devices Online", d: "Across 3 continents and 47 sites." },
      { v: "<3s", k: "Anomaly Detection", d: "From sensor reading to operator alert." },
    ],
  },
  {
    id: "harbor",
    num: "04",
    title: "Harbor",
    subtitle: "Internal developer platform",
    year: "2022",
    role: "Staff Engineer",
    timeline: "9 months",
    tools: "Kubernetes · Terraform · Go",
    tags: ["Platform", "Infrastructure"],
    desc: "A self-service platform that gave 80 engineers production-grade Kubernetes without learning Kubernetes.",
    art: "art-4",
    overview: "Harbor is an opinionated platform layer over Kubernetes. Engineers describe a service in 10 lines of YAML; Harbor provisions the namespace, the secrets, the ingress, the metrics, the alerts, and the on-call rotation.",
    problem: "Every team needed Kubernetes literacy to ship a service. We were burning hundreds of senior-engineer hours per quarter on the same five tickets.",
    process: "I led the platform team through interviews with every product team, mapped the 80% common path, and shipped a CLI plus web console that handled it. Power users could still drop down to raw K8s manifests when they needed to.",
    outcomes: [
      { v: "10×", k: "Faster Onboarding", d: "From 2 weeks to 1 day for a new service." },
      { v: "80", k: "Engineers Served", d: "Across 14 product teams." },
      { v: "94%", k: "Satisfaction Score", d: "From quarterly internal NPS." },
    ],
  },
  {
    id: "kestrel",
    num: "05",
    title: "Kestrel",
    subtitle: "ML feature store",
    year: "2022",
    role: "Senior Engineer",
    timeline: "6 months",
    tools: "Python · Spark · Redis",
    tags: ["Data", "ML Infrastructure"],
    desc: "A feature store that unified offline training and online serving for a recommendations team that owned 14 models.",
    art: "art-5",
    overview: "Kestrel is the bridge between batch training data and low-latency online inference. It lets data scientists author a feature once and consume it from both worlds with the same API.",
    problem: "Training-serving skew was eating model quality. Features computed in Spark for training drifted from features computed in Java for serving, and nobody could tell which features were even shared.",
    process: "I designed the feature DSL and the dual-store architecture (Parquet offline, Redis online), wrote the Spark and online runtimes, and migrated three of the 14 models as the proof. The remaining eleven followed within the quarter.",
    outcomes: [
      { v: "0", k: "Skew Incidents", d: "After all 14 models migrated." },
      { v: "14", k: "Models Served", d: "From a single feature definition." },
      { v: "+8.2%", k: "Lift in Recommendations", d: "From skew elimination alone." },
    ],
  },
];

const EXPERIENCE = [
  {
    period: "2023 — Now",
    now: true,
    role: "Senior Software Engineer",
    company: "Stealth fintech",
    location: "Remote",
    desc: "Leading backend platform for a real-time reconciliation product. Designed the event-streamed ledger that processes 4M+ transactions per day. Mentoring two engineers and shaping the technical direction of the platform team.",
    tags: ["TypeScript", "Kafka", "PostgreSQL", "AWS"],
  },
  {
    period: "2021 — 2023",
    role: "Software Engineer",
    company: "Helix Systems",
    location: "Berlin",
    desc: "Founding engineer on Atlas, an internal workflow automation platform now used across the company. Built both the Go execution engine and the React control plane. Partnered with five product teams to migrate their pipelines.",
    tags: ["Go", "React", "gRPC", "Kubernetes"],
  },
  {
    period: "2020 — 2021",
    role: "Full Stack Engineer",
    company: "Mercator Logistics",
    location: "Madrid",
    desc: "Shipped a fleet observability pipeline that compressed industrial telemetry 80x at the edge. Owned the Rust agent and the TimescaleDB schema. Mentored two interns through their first production deploys.",
    tags: ["Rust", "TimescaleDB", "WebAssembly"],
  },
  {
    period: "2019 — 2020",
    role: "Software Engineer",
    company: "Foundry Labs",
    location: "London",
    desc: "First job out of school. Worked on an internal developer platform serving 80 engineers across 14 product teams. Owned the CLI tooling and the web console.",
    tags: ["Go", "TypeScript", "Kubernetes"],
  },
  {
    period: "2015 — 2019",
    role: "B.Sc. Computer Science",
    company: "Université Paris-Saclay",
    location: "France",
    desc: "First-class honours. Final-year project on distributed consensus protocols, supervised by the LRI systems group. Co-founded the campus dev society and ran a weekly hack night.",
    tags: ["Distributed Systems", "Algorithms"],
  },
];

const SKILLS = {
  "Languages": ["TypeScript", "Go", "Python", "Rust", "SQL", "Bash"],
  "Backend": ["Node.js", "PostgreSQL", "Redis", "Kafka", "gRPC", "GraphQL", "REST"],
  "Infrastructure": ["Kubernetes", "Terraform", "AWS", "GCP", "Docker", "GitHub Actions"],
  "Frontend": ["React", "Next.js", "Astro", "Tailwind", "TypeScript"],
  "Practices": ["System Design", "Event-Driven Architecture", "DDD", "Mentoring", "Technical Writing"],
};

const TOOLS = [
  { n: "VS Code", c: "Editor" },
  { n: "Linear", c: "Planning" },
  { n: "Figma", c: "Design" },
  { n: "Notion", c: "Docs" },
  { n: "Datadog", c: "Observability" },
  { n: "Vercel", c: "Hosting" },
];

window.PROJECTS = PROJECTS;
window.EXPERIENCE = EXPERIENCE;
window.SKILLS = SKILLS;
window.TOOLS = TOOLS;
